# Generated by Django 4.1.7 on 2023-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('Full_name', 'Full Name'), ('Job', 'Job'), ('Email', 'Email'), ('Phone_number', 'Phone Number'), ('Company_name', 'Company Name'), ('Text', 'Text'), ('Number', 'Number'), ('Address', 'Address')], max_length=255),
        ),
    ]
